version: 2.1

orbs:
  cst: cst/framework@1

workflows:
  version: 2
  yeet-le-jobs:
    jobs:
      - cst/enforce-gem-version-bump
      - cst/rspec-ruby:
          rspec-system-args: "SIMPLE_COV_RUN=true"
          cc-report-collect-ruby: "3.1.0"
          matrix:
            parameters:
              ruby-version: ["3.0.0", "3.0.3", "3.1.0", "3.2.0"]
            alias: required-matrix-tests
          name: test-ruby<< matrix.ruby-version >>
      - cst/publish-gem:
          publish-git: true
          publish-default-gem: true
          requires:
            - required-matrix-tests
          filters:
            branches:
              only:
                - main
