# frozen_string_literal: true

require "thor_enhance"


module ThorEnhance
  class Sample < Thor
    thor_enhance_allow!

    class SubCommand < Thor
      thor_enhance_allow!

      desc "innard", "Validate that a subcommand works. This description can be as long as you want it to be."
      long_desc "Wow, This longer description will take precedence over the desc above. This is what will be shown in the readme autogenerated page. Try me out!"
      example "innard --count 5", desc: "Innard sub command with a count of 5"
      example "innard --count 35", desc: "Innard sub command with a count of 35"
      header name: "Deprecation warning", desc: "This command will get deprecated in the next major version"
      method_option :count, type: :numeric, readme: :skip
      def innard;end;
    end

    desc "sub", "Thor sub command validation for thor enhance"
    # example "sub", desc: "how to invoke sub command help"
    subcommand "sub", SubCommand

    desc "sample", "This Sample command does a lot of nothing"
    header name: "When should I use this?", desc: "Have you ever wanted your code to be useless? " \
      "Well, this command does absolutely nothing. This output is to say that this command does absolutely nothing"
    example "sample", desc: "yo yo ma"
    example "sample --boolean", desc: "yo yo ma"
    method_option :boolean, aliases: "-b", type: :boolean, desc: "Just a normal boolean", readme: :important
    def sample
      Kernel.puts "Executed Sample method"
    end
  end
end
